
- hosts: localhost
  tasks:
    - name: create the project
      reminder_project:
        addr: 127.0.0.1:8000
        state: present
        name: "awesome"
      environment:
          PYTHONPATH: /Users/remirey/dev/ansible-module-reminder
      register: res

    - debug:
        var: res

    - name: create an environment in the project
      reminder_environment:
        addr: 127.0.0.1:8000
        state: present
        project_name: "awesome"
        name: "staging"
      environment:
          PYTHONPATH: /Users/remirey/dev/ansible-module-reminder
      register: res

    - debug:
        var: res

    - name: retrieve the id of the reminder object for the project
      set_fact:
        reminder_id: "{{ res.environment.reminder.id }}"

    - debug:
        var: reminder_id

    - name: create a stack in enviroment
      reminder_stack:
        addr: 127.0.0.1:8000
        state: present
        reminder_id: "{{ reminder_id }}"
        name: "kafka"
      environment:
          PYTHONPATH: /Users/remirey/dev/ansible-module-reminder
      register: res

    - debug:
        var: res

    - set_fact:
        stack_id: "{{ res.stack.id }}"

  #    - name: create a stack section
  #      reminder_stack:
  #        addr: 127.0.0.1:8000
  #        state: present
  #        stack_id: "{{ stack_id }}"
  #        name: "Server list"
  #      environment:
  #          PYTHONPATH: /Users/remirey/dev/ansible-module-reminder
  #      register: res
  #
  #    - debug:
  #        var: res
  #
  #    - set_fact:
  #        stack_section_id: "{{ res.stack_section.id }}"
