
- hosts: localhost
  connection: local
  tasks:
    - name: create the project
      reminder_project:
        addr: 127.0.0.1:8000
        state: present
        name: "awesome"
      register: res

    - debug:
        var: res

    - name: create an environment in the project
      reminder_environment:
        addr: 127.0.0.1:8000
        state: present
        project_name: "awesome"
        name: "staging"
      register: res

    - debug:
        var: res

    - name: retrieve the id of the reminder object for the project
      set_fact:
        reminder_id: "{{ res.environment.reminder.id }}"

    - debug:
        var: reminder_id

    - name: create a stack in enviroment
      reminder_stack:
        addr: 127.0.0.1:8000
        state: present
        reminder_id: "{{ reminder_id }}"
        name: "kafka"
        logo: "kafka.png"
        hosts:
            - kafka-a-01.example.com
        urls:
            - http://kafka-a-01.example.com/
      register: res

    - debug:
        var: res

    - name: update a stack in enviroment
      reminder_stack:
        addr: 127.0.0.1:8000
        state: present
        reminder_id: "{{ reminder_id }}"
        name: "confluent-kafka"
        logo: "kafka.png"
        hosts:
            - kafka-a-01.example.com
            - kafka-a-01.example.com
        urls:
            - http://kafka-a-01.example.com/
            - http://kafka-a-02.example.com/
      register: res

    - name: ensure stack listed in group vars are created
      reminder_stack:
        addr: 127.0.0.1:8000
        state: present
        reminder_id: "{{ reminder_id }}"
        name: "{{ item.name }}"
        hosts: "{{ item.hosts }}"
        urls: "{{ item.urls }}"
        logo: "{{ item.logo }}"
      with_items: "{{ stacks }}"
      register: res

    - debug:
        var: res
